apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-task-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-task-manager
  template:
    metadata:
      labels:
        app: student-task-manager
    spec:
      containers:
        - name: student-task-container
          image: student-task-manager:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80